micronaut:
  application:
    name: access_manager

datasources:
  default:
    url: "${BASE_URL:`jdbc:postgresql://localhost:5432/postgres`}"
    driverClassName: org.postgresql.Driver
    username: postgres
    password: "${BASE_PASSWORD:`access_manager`}"
    dialect: POSTGRES

flyway:
  datasources:
    default:
      enabled: true
