micronaut:
  application:
    name: access_manager

  server:
    cors:
      enabled: true

  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      redoc:
        paths: classpath:META-INF/swagger/views/redoc
        mapping: /redoc/**
      public:
        paths: classpath:public
        mapping: /public/**
  security:
    intercept-url-map:
      - pattern: /swagger/*
        http-method: GET
        access:
          - isAnonymous()
      - pattern: /redoc/*
        http-method: GET
        access:
          - isAnonymous()
      - pattern: /public/*
        http-method: GET
        access:
          - isAnonymous()

datasources:
  default:
    url: ${JDBC_URL:`jdbc:h2:~/access_manager_db`}
    username: ${JDBC_USER:`user`}
    password: ${JDBC_PASSWORD:`password`}
    driverClassName: ${JDBC_DRIVER:org.h2.Driver}

jpa:
  default:
    entity-scan:
      packages: 'tech.crabs.access_manager.entities'
    properties:
      hibernate:
        hbm2ddl:
          auto: none
        show_sql: true

flyway:
  datasources:
    default:
      enabled: true

auth:
  login: "${ADMIN_LOGIN:`admin`}"
  password: "${ADMIN_PASSWORD:`admin`}"
